2.2.0~alpha blog post
ocaml/platform-blog pull request #92
Opened 2023-06-28 18:22 UTC by rjbou

:tada:

2023-06-29 08:36 UTC, rjbou commented on opam-2-2-0-alpha.md
> +> Special thanks to @cannorin for collaborating on this feature
```suggestion
> Special thanks to [@cannorin](htpps://github.com/@cannorin) for collaborating on this feature
```

2023-06-29 08:36 UTC, rjbou commented on opam-2-2-0-alpha.md
> +> Special thank to @zapashcanon for collaborating on this feature
```suggestion
> Special thanks to [@zapashcanon](https://github.com/@zapashcanon) for collaborating on this feature
```

2023-06-29 10:11 UTC, christinerose requested changes
Mostly minor changes in grammar/formatting/etc. A few syntax suggestions.

2023-06-29 10:11 UTC, christinerose commented on opam-2-2-0-alpha.md
> +Thanks for trying this new release out, and hoping you will enjoy the new features!
Minor suggestions: "Finally, we want to recognise everyone for their contribution to getting this alpha release over the line, especially OCamlPro and Tarides for their sponsorship of the project. Thank you!"

British spelling of recognise and replaced "and" with a comma

2023-06-29 10:11 UTC, christinerose commented on opam-2-2-0-alpha.md
> +You should then run:
```suggestion
1. From binaries: run
    ```
    bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --version 2.2.0~alpha"
    ```
Or download manually from [the Github "Releases" page](https://github.com/ocaml/opam/releases/tag/2.2.0-alpha) to your PATH.

2. From source, manually: see the instructions in the [README](https://github.com/ocaml/opam/tree/2.2.0-alpha#compiling-this-repo).

Then run:
```

There appears to be something going on with the code block here, but I can't find the extra ``` (unless I'm just not seeing it correctly. I don't have a preview, but the "or download..." and "2. From source..." are in blue, then the 

```
opam init --reinit -ni
```
is in white on my screen. (If that makes sense)

2023-06-29 10:11 UTC, christinerose commented on opam-2-2-0-alpha.md
> +Thanks for trying this new release out, and hoping you will enjoy the new features!
Also: "Thanks for trying this new release out, and we're hoping you will enjoy the new features!

(add "we're" between "and" and "hoping")

2023-06-29 10:11 UTC, christinerose commented on opam-2-2-0-alpha.md
> +  * ✘ Change `--base` into `--invariant`, column name and the content is invariant formula installed dependencies
```suggestion
  * ✘ Change `--base` into `--invariant`. The column name and the content are invariant formula-installed dependencies
```

2023-06-29 10:16 UTC, rjbou commented on opam-2-2-0-alpha.md
> +note](https://github.com/ocaml/opam/releases/tag/2.2.0-alpha).
```suggestion
We are happy to announce the alpha release of opam 2.2.0. It contains numerous
fixes, enhancements, and updates; including much-improved Windows support, addressing one of the most important pain points [identified by the OCaml community](https://discuss.ocaml.org/t/what-are-the-biggest-reasons-newcomers-give-up-on-ocaml/10958). You can view the full list of changes in the [release
note](https://github.com/ocaml/opam/releases/tag/2.2.0-alpha).
This alpha release is a significant milestone for the opam dev team which remains a long-term collaboration between OCamlPro ([@rjbou](https://github.com/rjbou), [@AltGr](https://github.com/AltGr)) and Tarides ([@dra27](https://github.com/dra27), [@kit-ty-kate](https://github.com/kit-ty-kate)), and the work of tens of community contributors.
```

2023-06-29 10:16 UTC, rjbou commented on opam-2-2-0-alpha.md
> +date: "2023-06-28"
```suggestion
date: "2023-06-30"
```

2023-06-29 11:08 UTC, rjbou reviewed
Thanks a lot @christinerose! I pushed most of the comments, and updated/answered others

2023-06-29 11:08 UTC, rjbou commented on opam-2-2-0-alpha.md
> +  * ✘ Change `--base` into `--invariant`, column name and the content is invariant formula installed dependencies
Oups forgot to add a note on that.

2023-06-29 11:08 UTC, rjbou commented on opam-2-2-0-alpha.md
> +And a bunch of new options:
```suggestion
Here are several of new options (possibly scripts breaking changes are marked with ✘):
```

2023-06-29 11:21 UTC, rjbou commented on opam-2-2-0-alpha.md
> +]
Usually (previous posts) we set in the authors the person(s) who wrote the post, not necessarily the reviewers. But it was maybe a mistake.
```suggestion
authors: [
  "David Allsopp - Tarides" {"mailto:david(at)tarides"}
  "Léo Andrès - OCamlPro" {"mailto:leo.andres(at)ocamlpro.com"}
  "Raja Boujbel - OCamlPro" {"mailto:raja.boujbel(at)ocamlpro.com"}
  "Basile Clément - OCamlPro" {"mailto:basile.clement(at)ocamlpro.com"}
  "Louis Gesbert - OCamlPro" {"mailto:louis.gesbert(at)ocamlpro.com"}
  "Dario Pinto" - OCamlPro" {"mailto:dario.pinto(at)ocamlpro.com"}
  "Christine Rose - Tarides" {"mailto:christine(at)tarides.com"}
  "Riku Silvola - Tarides" {"mailto:riku(at)tarides.com"}
]
```

2023-06-29 12:16 UTC, christinerose commented on opam-2-2-0-alpha.md
> +### How to test opam on Windows
So sorry for the misunderstanding. That's exactly what I mean. It's always lowercase like "opam" unless it's at the beginning of a sentence. Even in titles/headings/subheadings it's "opam."

2023-06-29 12:17 UTC, christinerose commented
Totally fine not to capitalize the title to make it consistent in the left panel. :)

2023-06-29 12:18 UTC, christinerose commented
All your suggestions look great @rikusilvola! 🙂

2023-06-29 16:18 UTC, bclement-ocp commented on opam-2-2-0-alpha.md
> +* These options can be combined
When installing or pinning a package using `opam install` or `opam pin`, opam normally only looks for opam files at the root of the installed package. With recursive pinning, you can now instruct opam to also look for `.opam` files in subdirectories, while maintaining the correct relationship between the `.opam` files and the package root for versioning and build purposes.

Recursive pinning is used with the following options to `opam pin` and `opam install`:
 * With `--recursive`, opam will look for `.opam` files recursively in all subdirectories.
 * With `--subpath <path>`, opam will only look for `.opam` files in the subdirectory `<path>`.

The two options can be combined: for instance, if your opam packages are stored as a deep hierarchy in the `opam` subdirectory of your project, give `opam pin . --recursive --subpath opam` a try!

2023-06-29 16:32 UTC, rjbou commented on opam-2-2-0-alpha.md
> +You can use these options with `opam pin` and `opam install`.
```suggestion
You can use these options with `opam pin`, `opam install`, and ``opam remove`.
```

2023-06-30 13:20 UTC, AltGr commented on opam-2-2-0-alpha.md
> +]
The point of `(à)` was to lightly obfuscate the addresses against scrapper bots; I think it serves little purpose to use `(at)` and not just `@`. Then again, it might have been useless already...

2023-06-30 13:32 UTC, AltGr commented
Thanks for all the proof-reading and corrections. I'd like to weigh in on some points:

- Raja was the release manager here, and that has been a long endeavour. This has been particularly heavy in the last few months as you can imagine.
- As such, and without minimising in any way the work of the rest of the team and the many contributors, I think she deserves to be put forward more for this release. I trust she wouldn't be one to take away credit from the rest of the team!

It would feel right to me that, at a minimum, she is left as only author for the release announcement: it's unfair to put last minute announcement contributions on the same level as years of dedicated work. I'd otherwise be OK with the contributors coming up with a wording that gives her due credit in the announcement body.

Then the release should be presented as a work of the opam team (Raja Boujbel, David Allsopp, Kate Deplaix, Louis Gesbert, in a united OCamlPro/Tarides collaboration) with the help of many contributors. And Jane Street must be thanked for their continued sponsorship. 

I don't want to propose direct wordings to avoid entering an edit war, but wish we could reach an agreement on this first ?

2023-06-30 14:49 UTC, AltGr commented on opam-2-2-0-alpha.md
> +note](https://github.com/ocaml/opam/releases/tag/2.2.0-alpha).
```suggestion
We are happy to announce the alpha release of opam 2.2.0. It contains numerous
fixes, enhancements, and updates; including much-improved Windows support, addressing one of the most important pain points [identified by the OCaml community](https://discuss.ocaml.org/t/what-are-the-biggest-reasons-newcomers-give-up-on-ocaml/10958). You can view the full list of changes in the [release
note](https://github.com/ocaml/opam/releases/tag/2.2.0-alpha).

This alpha release is a significant milestone, brought together by Raja Boujbel after years of work from the opam dev team (Raja Boujbel, David Allsopp, Kate Deplaix, Louis Gesbert, in a united OCamlPro/Tarides collaboration) with the help of many community contributors. We also thank JaneStreet for their continued sponsorship.
```

2023-06-30 14:50 UTC, AltGr commented on opam-2-2-0-alpha.md
> +* These options can be combined
Thanks this seems much clearer

2023-06-30 15:41 UTC, dra27 commented on opam-2-2-0-alpha.md
> +]
Yeah, surely somebody's AI by now is accurately interpreting email addresses. FWIW, in nearly all (all?) those cases we could link GitHub profiles instead, or do they have to be mailto?

2023-06-30 15:46 UTC, dra27 commented on opam-2-2-0-alpha.md
> +* These options can be combined
A thought - is it possibly clearer to demonstrate `--subpath` _first_ and then `--recursive`? IIUC we could show say a manual sub-path pin of `bar/bar.opam` in the example and then do the recursive pinning afterwards (and it will add another)?

2023-06-30 16:10 UTC, dra27 reviewed
This is really very nice, thank you 🙂 Others are paying close heed to acknowledgements and [SPAG](https://en.wiktionary.org/wiki/SPAG) - I've added a few more technical suggestions.

I wonder if it's worth emphasising even more that the Windows support is expected to get better/easier during the alpha release stage?

2023-06-30 16:10 UTC, dra27 commented on opam-2-2-0-alpha.md
> +You can use these options with `opam pin`, `opam install`, and ``opam remove`.
```suggestion
You can use these options with `opam pin`, `opam install`, and `opam remove`.
```

2023-06-30 16:10 UTC, dra27 commented on opam-2-2-0-alpha.md
> +$ opam pin --recursive . -n
I think it's always clearer in blogs/docs to use the full option names:
```suggestion
$ opam pin --recursive . --no-action
```

2023-06-30 16:10 UTC, dra27 commented on opam-2-2-0-alpha.md
> +ocaml -e '#use "topfind";; #require "digestif.ocaml";; #require "swhid";; Swhid_core.Object.pp Format.std_formatter (Result.get_ok (Swhid.Compute.directory_identifier_deep "."))'
Is there already an issue for having a command to do this in opam itself? (sorry, we may have discussed this ages ago!)

2023-06-30 16:10 UTC, dra27 commented on opam-2-2-0-alpha.md
> +archive all software source code in existence. This is done by first collecting
There's "first" here, but not then the "second" 🙂 I think the second part (which we're not doing yet) is having the tooling to add the SWHIDs in opam-repository. Is it worth mentioning that the aim is for that to follow the release of 2.2 (and then go on to say that you can manually add them to your packages right now, as shown below)?

2023-06-30 16:10 UTC, dra27 commented on opam-2-2-0-alpha.md
> +opam switch create ocaml --formula '"ocaml-variants" {>= "4.14.1"} | "ocaml-system"'
This part isn't new - is it worth turning this around, so starting with the `opam switch create --formula` and then explaining how that's been extended to `opam install` (IIRC you can't mix `--packages` and `--formula` in `opam switch create`? That might be worth noting that the version in `opam install` is a slightly more powerful UI?)

2023-06-30 16:10 UTC, dra27 commented on opam-2-2-0-alpha.md
> +  * ✘ Change `--base` into `--invariant`. `opam switch` _compiler_ column now contains installed packages that verifier invariant formula, and empty synopsis shows switch invariant.
It's very easy for me to say, but I think these would be better with a one-liner example added or description of what didn't work before! 🙂 Something like:
- `opam pin --current` - sample tree and explanation of the resulting state of the switch
- `opam pin remove foo.version` now removes the pin on `pkg` (i.e. describe the change rather than the option)
- `opam exec --no-switch` can probably be demonstrated quite nicely with an `env | grep -F opam` command or something to show that it's empty?
- `opam source --no-switch` - motivation is that you don't therefore need to have created any switch
- `opam switch -` - possibly worth referencing the same feature in git?
- etc

The change for base packages I would say either wants a section or to be omitted (remembering the pain that it was, I definitely see the desire to have it mentioned!)

2023-06-30 17:38 UTC, rjbou reviewed
Thanks @AltGr & @dra27 for the review! I'll integrate remaining ones on monday.

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +
````suggestion

It is possible to create a switch using a formula, for example:
 with `ocaml-variant` or `ocaml-system`, excluding `ocaml-base-compiler`:

```
opam switch create ocaml --formula '"ocaml-variants" {>= "4.14.1"} | "ocaml-system"'
```

This syntax is brought to install commands.
````

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +```
```suggestion
```

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +to `libc` dlls.
It is needed to compile/launch opam itself.

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +From here, you can try to install sunset repository packages. If any bug is
```suggestion
From here, you can try to install [sunset repository](https://discuss.ocaml.org/t/sunsetting-opam-repository-mingw/11632) packages. If any bug is
```

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +from [@fdopen](https://github.com/fdopen)) and [32/64 bit mingw-w64 packages](https://github.com/dra27/opam-repository) (by [@dra27](https://github.com/dra27)) is in the process of being merged.
```suggestion
from [@fdopen](https://github.com/fdopen)) and [32/64 bit mingw-w64 packages](https://github.com/dra27/opam-repository) (by [@dra27](https://github.com/dra27)) is in the process of being merged. By the release, main opam repository we expect opam repository to be Windows compliant.
```
@dra27 ?

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +in 2.2.0~alpha2 as another option.
It is not meant to be the default, if there is an already installation, we propose to user.

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +1. Check that you have all dependencies installed: Autoconf, Make, MinGW, or MSVC GCC
```suggestion
1. Check that you have all dependencies installed:
  * `autoconf`, `make`
  * MinGW compilers: `mingw64-x86_64-gcc-g++`, `mingw64-i686-gcc-g++`
  * Or If you want to use the MSVC port of OCaml, you'll need to install Visual Studio or Visual Studio Build Tools
```

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +5. Start your preferred Windows terminal (cmd or PowerShell), and initialise opam with the Windows _sunset_ repository:
cf comment :arrow_up:

2023-06-30 17:38 UTC, rjbou commented on opam-2-2-0-alpha.md
> +3. In the directory launch `make cold [OCAML_PORT=mingw64|mingw|msvc64|msvc|auto]`
I was worried that it would choose default cygwin compiler
```suggestion
3. In the directory launch `make cold`
```

2023-06-30 17:40 UTC, rjbou commented on opam-2-2-0-alpha.md
> +opam switch create ocaml --formula '"ocaml-variants" {>= "4.14.1"} | "ocaml-system"'
cf comment :arrow_up:

2023-07-03 10:07 UTC, rjbou commented on opam-2-2-0-alpha.md
> +archive all software source code in existence. This is done by first collecting
```suggestion
archive all software source code in existence. This is done by collecting
```
There is no second indeed, it was the introduction of the whole process. The `first` referred to the `from there` below.

2023-07-03 11:00 UTC, dra27 commented on opam-2-2-0-alpha.md
> +3. In the directory launch `make cold [OCAML_PORT=mingw64|mingw|msvc64|msvc|auto]`
Hopefully people won't have installed it - that's the `gcc-core` package in Cygwin (which isn't picked up by default).

2023-07-03 11:02 UTC, dra27 commented on opam-2-2-0-alpha.md
> +to `libc` dlls.
Ah, good point - we could instead have `make cold` pass `--with-private-runtime` to configure. The only caveat is that then you have to copy `opam.exe` and the generated runtime directory (this is what fdopen's opam64 distribution uses).

2023-07-03 11:03 UTC, dra27 commented on opam-2-2-0-alpha.md
> +ocaml -e '#use "topfind";; #require "digestif.ocaml";; #require "swhid";; Swhid_core.Object.pp Format.std_formatter (Result.get_ok (Swhid.Compute.directory_identifier_deep "."))'
Yeah, agreed - or perhaps the swhid package could have a binary to do the same?

2023-07-03 11:06 UTC, rjbou commented on opam-2-2-0-alpha.md
> +ocaml -e '#use "topfind";; #require "digestif.ocaml";; #require "swhid";; Swhid_core.Object.pp Format.std_formatter (Result.get_ok (Swhid.Compute.directory_identifier_deep "."))'
It is planned ;)

2023-07-03 11:20 UTC, rjbou commented on opam-2-2-0-alpha.md
> +to `libc` dlls.
```suggestion
> Hint: if you use the MinGW compiler, don't forget to add to your `PATH` the path to `libc` dlls (usually `C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\bin`). Or compile opam with `make cold CONFIGURE_ARGS=--with-private-runtime`, and if you change opam location, don't forget to copy `Opam.Runtime.amd64` (or `Opam.Runtime.i386`) with it.
```

2023-07-03 13:19 UTC, merged

2023-07-03 13:25 UTC, rjbou commented
Thanks all!!